### ISSUE TITLE
Some messages are not decrypted

### ISSUE THREAD

**Issue by ApostelPaulus** [WHAnonymous/Chat-API#1266]
Hi guys!

I have some problems with encryption with the newest version (2.5.5.4). Appearently some of the message are being decrypted, some are not.
In this case: I texted the number, message is received and decrypted. When my friend texts the same phone number, I receive it, but the second children (containing the decrypted message part) is missing. 

I have another phone number registered with the old version (2.5.4) of the chat-api. If we both text this number, everything works fine. But for a different phone number, which was registered with the 2.5.5.4 version, some messages aren't decrypted. 

Any known issues about that?

```
[2015-12-03 09:56:13] production.DEBUG: Array
(
    [tag] => message
    [attributeHash] => Array
        (
            [from] => 436607386561@s.whatsapp.net
            [type] => text
            [id] => EEAC025862455C15830
            [offline] => 0
            [t] => 1449136563
            [notify] => Bruce Wayne
        )

    [children] => Array
        (
            [0] => ProtocolNode Object
                (
                    [tag:ProtocolNode:private] => enc
                    [attributeHash:ProtocolNode:private] => Array
                        (
                            [v] => 1
                            [type] => pkmsg
                        )

                    [children:ProtocolNode:private] =>
                    [data:ProtocolNode:private] => 3^H~L| �^D^R!^E~R�~L�yE��Hf�o^X^^�^\Q�~L�.^T^T��~E�Y�^Q^R(^Z!^ED0n���^_~X��Y7�,���^P_~G�@�"~K~H�E]~Z�^S"B3
!^E�~^�=$1^N^NxWJ4~K@�~S�~A~U~A�t^E�A^Qao~Dw�h^P^C^X^@"^P~FS<,�pl^K,�^@~G^K��| {"�^E��~N](~E���^B0ɤ^A
                )

            [1] => ProtocolNode Object
                (
                    [tag:ProtocolNode:private] => body
                    [attributeHash:ProtocolNode:private] =>
                    [children:ProtocolNode:private] =>
                    [data:ProtocolNode:private] => hi
                )

        )

    [data] =>
)
[2015-12-03 09:56:26] production.DEBUG: Array
(
    [tag] => message
    [attributeHash] => Array
        (
            [from] => 4369910313201@s.whatsapp.net
            [type] => text
            [id] => 906CCE09484D1F06032
            [t] => 1449136580
            [notify] => Peter Parker
        )

    [children] => Array
        (
            [0] => ProtocolNode Object
                (
                    [tag:ProtocolNode:private] => enc
                    [attributeHash:ProtocolNode:private] => Array
                        (
                            [v] => 1
                            [type] => pkmsg
                        )

                    [children:ProtocolNode:private] =>
                    [data:ProtocolNode:private] => 3^H�~_�^D^R!^E�T~L^G�mH.w�   �Cq������:b~RF^A�m�^C�5r^Z!^EB6~E�~N^H�^F~GB[�^Fy~D~N~Z^Sy^U��"y~\:~]~D�6~ZA"B3
!^E^Z_F��~B~_/P��G^P"(^Q~B~@^AO�f�ǩ�T~SŽ�^S^P^@^X^@"^Pp�s^Nb�3����=~P!~Wu�~_�vCqP((~X~W��^C0ɤ^A
                )

        )

    [data] =>
)

[2015-12-03 09:56:26] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getData() on null' in /var/www/phoenix/app/Console/Commands/WhatsAppPoll.php:219
Stack trace:
#0 {main}
```

Curve & Protobuf are installed and loaded, here the (skipped) output of ```php -m```:

```
php -m
[PHP Modules]
apc

...skipped for sake of reading...

Core
ctype
curl
curve25519
date
dba

...skipped for sake of reading...

PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
readline

...skipped for sake of reading...

```

**Comment by Jonathan313** [comment]
@mgp25  is already working on it. Have patient !

**Comment by fsadario** [comment]
Got same problem, with most numbers works flawless, but got this problem on a few. There's the log:

```
rx  <message from="5493624668246@s.whatsapp.net" type="text" id="B5569CA072A95909B1E" t="1449227473" notify="Francisco Billordo">
rx    <enc v="1" type="pkmsg">3ÑË!Õ
œi×qEõÊ:Ï‹°_ç"E*R¶²?Ú+¹%ÿP!ÐlQr‘·Ý©6¹ÚI3Me]y7ã·wñÍ
†éÝ"B3
!X¥ôU!u—´
ª,´ÕÒKA†~ÊÉ¢PM¬Ì/

tx  <ack to="5493624668246@s.whatsapp.net" class="message" id="B5569CA072A95909B1E" t="1449227473"></ack>

tx  <iq id="35" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="5493624668246@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="35">
rx    <list>
rx      <user jid="5493624668246@s.whatsapp.net">
rx        <registration>Uùt</registration>
rx        <type></type>
rx        <identity>ÐlQr‘·Ý©6¹ÚI3Me]y7ã·wñÍ
†éÝ</identity>
rx        <skey>
rx          <id>   </id>
rx          <value>¬<ùZ#ßDŠŒé´ª<¬ìá_qPXq™X(˜gÀ'</value>
rx          <signature>ÝŠƒøô8
IÕ‰@ïçfjÞ-Òw’§‰=RzaW±°üýXºúõ¦¹kA¾ºŠ7©X4[Ãx;=­ƒ…Ê“m²™
</signature>
rx        </skey>
rx        <key>
rx          <id>qN</id>
rx          <value>ƒl€Z[Õ&¿Ü1BðZÃüÚ«Ö!W§tš}ëø&,</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

tx  <ack to="5493624668246@s.whatsapp.net" class="message" id="B5569CA072A95909B1E" t="1449227473"></ack>

-> Decrypted Message: No such signedprekey with id: 10048 - /home/ubuntu/EP/SqliteAxolotlStore.php - 203Message B5569CA072A95909B1E could not be decrypted, sending retry.

tx  <receipt id="B5569CA072A95909B1E" to="5493624668246@s.whatsapp.net" type="retry" t="1449227473">
tx    <retry v="1" count="26" id="B5569CA072A95909B1E" t="1449227473"></retry>
tx    <registration>×rX	</registration>
tx  </receipt>
```

Decryption working with others numbers. So is not an extension problem i think. 
Thanks you for your time.

**Comment by mgp25** [comment]
Remove `axolotl.db` and run it again, it should solve it. Im right now trying to solve other stuff, when its done i'll check this again.

(check other opened issues as it might be related)

Regards

**Comment by ApostelPaulus** [comment]
I have removed `axolotl.db`, but still the same issue. I have already checked all related issues, but didn't find a solution yet -.-

**Comment by Jonathan313** [comment]
Same here dude. New code is blocking numbers  + group message not showing correctly I mean in encrypted format. ~_~!

**Comment by mgp25** [comment]
We know, we are working hard on this, spending our free time to make this API possible, but people is getting annoying being so impatiente

**Comment by Jonathan313** [comment]
Not really dude. You closed that issue that's why we said. Sorry :/

**Comment by mgp25** [comment]
@Jonathan313 all closed issues are already implemented or fixed in the next release, its easier to manage for me. If everything is okay, i guess the next release should be alive on 30 of December.

Regards

**Comment by Jonathan313** [comment]
@mgp25  :  Still that group message problem is there even you updated the code. Personal messages are decrypted but the group messages are still encrypted.

**Comment by mgp25** [comment]
@Jonathan313 _sigh_... read my comment again
